### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/vesuvio#26]
Read me is out of date given the repo updates, and doesn't contain standard content.

Edit: I've updated the readme. Please review and test the use of the `mvesuvo` package per the instructions.

Also, I have left the bulk of the old readme there. Please modify/remove this as required.

**Comment by GuiMacielPereira** [comment]
- Opened a PR for this but closed it and decided to push to main directly in commit fa87518929a943087387bae987fca52a64a25d2e
- Simply removed outdated README section
