### ISSUE TITLE
Replace github runner token with jinja template

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/vesuvio#89]
Currently in our [runner github script](https://github.com/mantidproject/vesuvio/blob/main/runner/ansible/setup/setup.sh) there is the Github runner secret.

This needs to be replaced with a jinja template so that the github runner token can instead be specified in the ansible inventory file.

**Comment by GuiMacielPereira** [comment]
The changes in https://github.com/mantidproject/vesuvio/pull/124 make the tests run on GitHub host 'ubuntu-latest`, rather than being self-hosted as it was before. Therefore this issue is no longer relevant
